
version: '3'

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/authSAS.proto --go_out=./result/go/ --go_opt=paths=source_relative --go-grpc_out=./result/go/ --go-grpc_opt=paths=source_relative